const test = {
  created_at: 'Wed Apr 14 20:44:25 +0000 2021',
  id: 1382434592364376000,
  id_str: '1382434592364376068',
  text:
    "RT @riktroiani: �🌈 La #Danimarca sospenderà definitivamente l'uso del vaccino anti-#Covid di #AstraZeneca. Lo ha reso noto l'emittente telev...",
  source:
    '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 1322543941,
    id_str: '1322543941',
    name: 'daniele 1992',
    screen_name: 'daniele19921',
    location: 'italia',
    url: null,
    description: 'i am waiting for a girlfriend;) #jesuiscatholicque',
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 2667,
    friends_count: 3150,
    listed_count: 110,
    favourites_count: 653,
    statuses_count: 301353,
    created_at: 'Tue Apr 02 13:52:41 +0000 2013',
    utc_offset: null,
    time_zone: null,
    geo_enabled: true,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url:
      'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https:
      'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url:
      'http://pbs.twimg.com/profile_images/1342085226839891968/-qYuQWVO_normal.jpg',
    profile_image_url_https:
      'https://pbs.twimg.com/profile_images/1342085226839891968/-qYuQWVO_normal.jpg',
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    withheld_in_countries: [],
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweeted_status: {
    created_at: 'Wed Apr 14 10:42:50 +0000 2021',
    id: 1382283197816377300,
    id_str: '1382283197816377345',
    text:
      "�📦 La #Danimarca sospenderà definitivamente l'uso del vaccino anti-#Covid di #AstraZeneca. Lo ha reso noto l'emitten... https://t.co/lIBNnqAoHO",
    source:
      '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: true,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 126351209,
      id_str: '126351209',
      name: 'Rik Troiani',
      screen_name: 'riktroiani',
      location: 'Italia',
      url: 'http://www.stadiogoal.com',
      description:
        'Liberale, democratico. Rispetto ed educazione la base.\n' +
        'Condivido #news, offro spunti #social\n' +
        'Opinionista (da casa). RT are not endorsement',
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 5332,
      friends_count: 284,
      listed_count: 85,
      favourites_count: 44474,
      statuses_count: 110843,
      created_at: 'Thu Mar 25 15:47:35 +0000 2010',
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'B2DFDA',
      profile_background_image_url:
        'http://abs.twimg.com/images/themes/theme13/bg.gif',
      profile_background_image_url_https:
        'https://abs.twimg.com/images/themes/theme13/bg.gif',
      profile_background_tile: false,
      profile_link_color: '93A644',
      profile_sidebar_border_color: 'EEEEEE',
      profile_sidebar_fill_color: 'FFFFFF',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url:
        'http://pbs.twimg.com/profile_images/1345814584846917635/wDJPl9K6_normal.jpg',
      profile_image_url_https:
        'https://pbs.twimg.com/profile_images/1345814584846917635/wDJPl9K6_normal.jpg',
      profile_banner_url:
        'https://pbs.twimg.com/profile_banners/126351209/1583760097',
      default_profile: false,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    extended_tweet: {
      full_text: `�📦 La #Danimarca sospenderà definitivamente l'uso del vaccino anti-#Covid di #AstraZeneca. Lo ha reso noto l'emittente televisiva pubblica
    v2, citando fonti anonime, secondo quanto riporta il Guardian.`,
      display_text_range: [Array],
      entities: [Object],
    },
    quote_count: 0,
    reply_count: 7,
    retweet_count: 37,
    favorite_count: 57,
    entities: {
      hashtags: [Array],
      urls: [Array],
      user_mentions: [],
      symbols: [],
    },
    favorited: false,
    retweeted: false,
    filter_level: 'low',
    lang: 'it',
  },
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: {
    hashtags: [[Object], [Object], [Object]],
    urls: [],
    user_mentions: [[Object]],
    symbols: [],
  },
  favorited: false,
  retweeted: false,
  filter_level: 'low',
  lang: 'it',
  timestamp_ms: '1618433065869',
};
